runtime: python39
# entrypoint: python3 -m app.main
entrypoint: gunicorn -b :$PORT main:app

handlers:
  - url: /.*
    script: auto

env_variables:
  FLASK_ENV: "production"
  GOOGLE_CLOUD_PROJECT: "gae-reviewspot-api"
  # FLASK_ENV: 'development'
